spring:
  application:
    name: openstreetmap-api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: changeset-upload-path
              uri: ${OSM_API_URL:https://api.openstreetmap.org}
              predicates:
                - Path=/api/{api-version}/changeset/{changeset-id}/upload
              filters:
                - name: ChangesetUploadPreFilter
                - name: ChangesetUploadPostFilter

            - id: default
              uri: ${OSM_API_URL:https://api.openstreetmap.org}
              predicates:
                - Path=/api/{api-version}/**

          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowed-origins: "http://localhost:3000"
                allowed-methods: [ GET, POST, PUT, PATCH, DELETE, OPTIONS ]
                allowed-headers: "*"
                allow-credentials: true

          default-filters:
            - SetResponseHeader=access-control-allow-origin, http://localhost:3000
  http:
    codecs:
      max-in-memory-size: 1GB

openstreetmap-api-gateway:
  openstreetmap-quality-framework-url: ${OSM_QUALITY_FRAMEWORK_URL}
  openstreetmap-notification-service-url: ${OSM_NOTIFICATION_SERVICE_URL:unknown}